### ISSUE TITLE
make Hydra-Multi

### ISSUE THREAD

**Issue by svsgvarma** [arq5x/Hydra#14]
Hi,
I try to install Hydra on Linux command line as below, I had this error! I have no clue what is wrong, any suggestions?
##### ------error-----

**~/Hydra-Multi$ git clone https://github.com/arq5x/Hydra**
Cloning into 'Hydra'...
remote: Counting objects: 728, done.
remote: Total 728 (delta 0), reused 0 (delta 0), pack-reused 728
Receiving objects: 100% (728/728), 347.26 KiB | 0 bytes/s, done.
Resolving deltas: 100% (441/441), done.
Checking connectivity... done.
**~/Hydra-Multi$ cd Hydra/**
**~/Hydra-Multi/Hydra$ make**
[ -d obj ] || mkdir -p obj
[ -d bin ] || mkdir -p bin
# Building Hydra suite:
- Building in src/Hydra
  - compiling HydraMain.cpp
  - compiling Hydra.cpp
  - compiling Sort.cpp
  - compiling Ancillary.cpp
  - compiling gzstream.cpp
  - linking hydra-ext
    ../../obj//gzstream.o: In function `gzstreambuf::underflow()':
    gzstream.cpp:(.text+0x7b): undefined reference to`gzread'
    ../../obj//gzstream.o: In function `gzstreambuf::open(char const*, int)':
    gzstream.cpp:(.text+0x112): undefined reference to`gzopen'
    ../../obj//gzstream.o: In function `gzstreambuf::close()':
    gzstream.cpp:(.text+0x18f): undefined reference to`gzclose'
    ../../obj//gzstream.o: In function `gzstreambuf::flush_buffer()':
    gzstream.cpp:(.text+0x2bb): undefined reference to`gzwrite'
    collect2: error: ld returned 1 exit status
    Makefile:37: recipe for target 'hydra-ext' failed
    make[1]: **\* [hydra-ext] Error 1
##### ------------------------------

/G Varma

**Comment by ml4wc** [comment]
You probably need the zlib compression library, use your package manager (yum or apt-get) to install it.

**Comment by svsgvarma** [comment]
I have installed Zlib package for ubuntu and even full package from different sources,

ex: https://geeksww.com/tutorials/libraries/zlib/installation/installing_zlib_on_ubuntu_linux.php

However, I have the same error repeating while using command line $ make  or $ make all

**Comment by ml4wc** [comment]
The error is coming from the fact that your compiler is not linking the zlib library correctly during the make command:

1) try manually adding -lz to the make command in the CXXFLAGS line or directly to the $make call

2) This could potentially be a version thing, so maybe try to dev version of zlib with a package manager (apt-get) to sudo apt-get install zlib1g and sudo apt-get install zlib1g and  zlib1g-dev 

3) try manually compiling source that contains the calls to the zlib library to make sure that your compiler is linking the library at all

**Comment by timothyjamesbecker** [comment]
If it helps: under Ubuntu 14 LTS, I was not able to build with g++4.8 and it is totally a linking error with zlib when you try to compile manually with the g++ command.  I have run into this problem before compiling TIGRA so it doesn't segfault.  My fix was to go into /src/Hydra/Makefile and edit the top line where you select which compiler you want.

CXX = g++-4.4

instead of

CXX = g++ (which will default to 4.8+ on 14LTS and above)

You will have to first install the lower version g++ via apt-get:

apt-get install g++-4.4

Hope this helps you compile/understand the issues!
